# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Slower Than Ever
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
# baseurl: "/bay" # the subpath of the site
url: "https://se-ize.github.io" # the base hostname & protocol for the site
og_image: ./assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: idshkc@gmail.com
      link: mailto:idshkc@gmail.com
    - name: WeChat
      value: se-ize
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/se-ize
      username: "@se-ize"
    - name: Facebook
      link: http://facebook.com/se-ize
    - name: LinkedIn
      link: http://linkedin.com/in/se-ize
    - name: GitHub
      link: http://github.com/se-ize
    - name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
